Repository cse110-sp24-group30/warmup-exercise, pull requests merged in 2024-04, with the labels that each got.

#7 set up main files for development
  app.js
  index.html
  styles.css
Labels: frontend, backend

#9 Update hard-coded-tasks.JSON
  task-list/hard-coded-tasks.JSON
Labels: design

#16 Set up Canvas
  index.html
  styles.css
Labels: frontend

#30 Add edit delete entries
  app.js
  index.html
  styles.css
Labels: backend

#33 css update
  index.html
  styles.css
Labels: frontend

#45 Pokemon animations
  app.js
  index.html
  styles.css
Labels: frontend
